name: Workflow
on:
  push:
    branches:
      - feature-jm

jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Hola mundo
        run: echo "Hola mundo"

      
